from django.db import models
class CultivarGroup(models.Model):
	TSWV_resistance = models.BooleanField(max_length=255, null=False)
	yield_lbs_per_acre = models.FloatField(max_length=255, null=False)
	days_to_mature = models.IntegerField(default=99)
	Desired_Ca = models.FloatField(max_length=255, null=False)
	white_mold_resistance = models.BooleanField(max_length=255, null=False)
	CBR_resistance = models.BooleanField(max_length=255, null=False)
	limb_rot_resistance = models.BooleanField(max_length=255, null=False)
	def __str__(self):
		return "{} - {}".format(self.TSWV_resistance, self.yield_lbs_per_acre, self.days_to_mature, self.Desired_Ca, self.white_mold_resistance, self.CBR_resistance, self.limb_rot_resistance)
class SingleMound(models.Model):
	cultivar_group = models.CultivarGroupField(max_length=255, null=False)
	plot_of_land = models.PlotOfLandField(max_length=255, null=False)
	x_coord_in_plot = models.IntegerField(default=99)
	y_coord_in_plot = models.IntegerField(default=99)
	days_since_h2o_input = models.IntegerField(default=99)
	last_h2o_input_amt = models.FloatField(max_length=255, null=False)
	days_since_planting = models.IntegerField(default=99)
	soil_moist = models.FloatField(max_length=255, null=False)
	plant_height = models.FloatField(max_length=255, null=False)
	leaf_discolor = models.CharField(max_length=255, null=False)
	avg_sunlight = models.FloatField(max_length=255, null=False)
	avg_soil_temp = models.FloatField(max_length=255, null=False)
	avg_air_temp = models.FloatField(max_length=255, null=False)
	leaf_discolor_resolved = models.BooleanField(max_length=255, null=False)
	peanut_inoculant_applied = models.BooleanField(max_length=255, null=False)
	last_date_local_observation = models.DateField(max_length=255, null=False)
	soil_ph = models.DateField(max_length=255, null=False)
	def __str__(self):
		return "{} - {}".format(self.cultivar_group, self.plot_of_land, self.x_coord_in_plot, self.y_coord_in_plot, self.days_since_h2o_input, self.last_h2o_input_amt, self.days_since_planting, self.soil_moist, self.plant_height, self.leaf_discolor, self.avg_sunlight, self.avg_soil_temp, self.avg_air_temp, self.leaf_discolor_resolved, self.peanut_inoculant_applied, self.last_date_local_observation, self.soil_ph)
class PlotOfLand(models.Model):
	farmer_id = models.FarmerIdField(max_length=255, null=False)
	num_columns_full = models.IntegerField(default=99)
	approx_gps = models.CharField(max_length=255, null=False)
	num_rows_full = models.IntegerField(default=99)
	x_dist_between_mounds = models.FloatField(max_length=255, null=False)
	y_dist_between_mounds = models.FloatField(max_length=255, null=False)
	diameter_mounds = models.FloatField(max_length=255, null=False)
	peanuts_seeds_per_mound = models.IntegerField(default=99)
	def __str__(self):
		return "{} - {}".format(self.farmer_id, self.num_columns_full, self.approx_gps, self.num_rows_full, self.x_dist_between_mounds, self.y_dist_between_mounds, self.diameter_mounds, self.peanuts_seeds_per_mound)
class FarmerId(models.Model):
	user_id = models.CharField(max_length=255, null=False)
	first_name = models.CharField(max_length=255, null=False)
	last_name = models.CharField(max_length=255, null=False)
	email = models.CharField(max_length=255, null=False)
	phone_number = models.CharField(max_length=255, null=False)
	def __str__(self):
		return "{} - {}".format(self.user_id, self.first_name, self.last_name, self.email, self.phone_number)
